name: "Draft new release"

on:
  push:
    branches:
      - release/v*.*.*

jobs:
  draft-new-release:
    name: "Draft new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract version from branch name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          VERSION=${BRANCH_NAME#release/}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Validate the version
        id: regex-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ env.RELEASE_VERSION }}
          regex: '^v\d+(\.\d+){2}$'

      - name: Create pull request
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ env.RELEASE_VERSION }}
          base: main
          title: Release version ${{ env.RELEASE_VERSION }}
          reviewers: ${{ github.actor }}
