name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release'
        required: true

jobs:
  draft-new-release:
    name: "Draft new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate the version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.inputs.version }}
          regex: '^v\d+(\.\d+){2}$'

      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.version }}

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: main
          title: Release version ${{ github.event.inputs.version }}
          reviewers: ${{ github.actor }}
